# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CI Computer Girls
email: csuci.computer.girls@gmail.com
description: >
  Wow this club is so cool.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ci-computer-girls.github.io" # the base hostname & protocol for your site
twitter_username: cicomputergirls
github_username: ci-computer-girls

# Build settings
markdown: kramdown
